apiVersion: v1
kind: PersistentVolume
metadata:
  name: qlik-docs
spec:
  claimRef:
    namespace: default
    name: qlik-docs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/docs/
