apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
spec:
  template:
    metadata:
      labels:
        app: engine
        service: engine
        qix-engine: ""
    spec:
      containers:
      - name: engine
        image: "qlikcore/engine:12.190.0"
        imagePullPolicy: IfNotPresent
        args: ["-S", "AcceptEULA=no", "-S", "DocumentDirectory=/data/apps", "-S", "SystemLogVerbosity=4", "-S", "EnableFilePolling=1"]
        ports:
        - containerPort: 9076
        volumeMounts:
          - name: data
            mountPath: /data/apps
        readinessProbe:
          httpGet:
            path: /health
            port: 9076
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: qlik-docs
