apiVersion: v1
kind: Service
metadata:
  name: engine2
  labels:
    app: engine2
spec:
  type: NodePort
  ports:
    - port: 9076
      targetPort: 9076
      protocol: TCP
      name: qix
  selector:
    app: engine
